### ISSUE TITLE
快捷键重复问题

### ISSUE THREAD

**Issue by struggle3** [yanxiaodi/vscode-translator-helper#1]
你好，这个翻译插件在ubuntu操作系统下面Alt+T快捷键不起作用，原因是Alt+T是打开vs code终端快捷键。

**Comment by yanxiaodi** [comment]
谢谢反馈，请问ubuntu下建议用什么快捷键好呢？

**Comment by struggle3** [comment]
@yanxiaodi vs code没有这个快捷键，但是在ubuntu操作系统下面就可以通过alt+t打列终端菜单，我怀疑是系统的原因。

**Comment by yanxiaodi** [comment]
@struggle3 能否试试在keybindings里换一下快捷键，如果没法改终端菜单的，可以尝试把Translator Helper的快捷键改成别的，不冲突就可以。
