### ISSUE TITLE
功能请求：增加 选中悬浮翻译，并将翻译内容复制到粘帖板，

### ISSUE THREAD

**Issue by pgy866** [yanxiaodi/vscode-translator-helper#16]
功能请求：增加 选中悬浮翻译，并将翻译内容复制到粘帖板，

**Comment by yanxiaodi** [comment]
Hi @pgy866 , 多谢建议！最近会继续完善这个项目，我看看能不能加上这个功能。

**Comment by yanxiaodi** [comment]
Hi @pgy866 已更新了一个版本，现在可以支持选中悬浮翻译了，点击Copy可以复制到剪贴板。
