### ISSUE TITLE
Yanxiaodi你好,能否设置Shift-ALT-T快捷键为当前设置的反方向的语言的相互翻译?

### ISSUE THREAD

**Issue by gitvscodeserver** [yanxiaodi/vscode-translator-helper#3]
1.每次我英文翻译为中文,我设置一次user.setting.json.
2.而我每次要把中文翻译为英文,需要重新修改一次上述设置,user.setting.json,并且需要重新启动一次vscode.
3.能否ALT-T是一个翻译方向,而Shift-ALT-T是反方向的翻译.这样,我就不用再去设置与重启vscode 了.

祝顺利!

**Comment by yanxiaodi** [comment]
前几天已经更新了。FYI: #2
