### ISSUE TITLE
Please add shortcut for Translate to clipboard.

### ISSUE THREAD

**Issue by ww7** [yanxiaodi/vscode-translator-helper#4]
Every translation clicks is annoying.
Please add shortcut for Translate to clipboard.

**Comment by yanxiaodi** [comment]
@ww7 sorry could you please clarify your requirement? Do you mean clicking the translated word on the status bar? What do you think if adding a configuration to copy the translated text automatically?
Thanks.

**Comment by yanxiaodi** [comment]
Hi @ww7 I have updated a version and now if you press Ctrl+T, the translated text will be automatically copied to clipboard.
Also it now supports selection-translation. If you select a word or a sentence, you can see the translation if you hover your mouse on the text.
